// Copyright (c) 2024 ROS2 OpenHarmony Port Project
// visualization_msgs/srv/GetInteractiveMarkers_Response type

#ifndef VISUALIZATION_MSGS__SRV__GETINTERACTIVEMARKERS_RESPONSE_H_
#define VISUALIZATION_MSGS__SRV__GETINTERACTIVEMARKERS_RESPONSE_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_runtime_c/visibility_control.h"
#include "visualization_msgs/msg/rosidl_generator_c__visibility_control.h"
#include "visualization_msgs/msg/interactive_marker.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct visualization_msgs__srv__GetInteractiveMarkers_Response
{
  uint64_t sequence_number;
  visualization_msgs__msg__InteractiveMarker__Sequence markers;
} visualization_msgs__srv__GetInteractiveMarkers_Response;

typedef struct visualization_msgs__srv__GetInteractiveMarkers_Response__Sequence
{
  visualization_msgs__srv__GetInteractiveMarkers_Response * data;
  size_t size;
  size_t capacity;
} visualization_msgs__srv__GetInteractiveMarkers_Response__Sequence;

ROSIDL_GENERATOR_C_PUBLIC_visualization_msgs
bool visualization_msgs__srv__GetInteractiveMarkers_Response__init(visualization_msgs__srv__GetInteractiveMarkers_Response * msg);

ROSIDL_GENERATOR_C_PUBLIC_visualization_msgs
void visualization_msgs__srv__GetInteractiveMarkers_Response__fini(visualization_msgs__srv__GetInteractiveMarkers_Response * msg);

ROSIDL_GENERATOR_C_PUBLIC_visualization_msgs
visualization_msgs__srv__GetInteractiveMarkers_Response * visualization_msgs__srv__GetInteractiveMarkers_Response__create(void);

ROSIDL_GENERATOR_C_PUBLIC_visualization_msgs
void visualization_msgs__srv__GetInteractiveMarkers_Response__destroy(visualization_msgs__srv__GetInteractiveMarkers_Response * msg);

ROSIDL_GENERATOR_C_PUBLIC_visualization_msgs
bool visualization_msgs__srv__GetInteractiveMarkers_Response__Sequence__init(
  visualization_msgs__srv__GetInteractiveMarkers_Response__Sequence * array, size_t size);

ROSIDL_GENERATOR_C_PUBLIC_visualization_msgs
void visualization_msgs__srv__GetInteractiveMarkers_Response__Sequence__fini(
  visualization_msgs__srv__GetInteractiveMarkers_Response__Sequence * array);

#ifdef __cplusplus
}
#endif

#endif  // VISUALIZATION_MSGS__SRV__GETINTERACTIVEMARKERS_RESPONSE_H_
