#!/usr/bin/env python3
"""
Generate logging_macros.h from EmPy template.
This script is a simplified version that bypasses EmPy for now.
"""

import argparse
import os
import sys


def generate_logging_macros(template_path, output_path):
    """
    Generate logging_macros.h from template.

    For initial porting, we generate a simplified version without EmPy.
    TODO: Integrate EmPy for full template expansion.
    """

    # Read template (for validation)
    if not os.path.exists(template_path):
        print(f"ERROR: Template not found: {template_path}", file=sys.stderr)
        return 1

    # Generate simplified logging_macros.h
    # This is a minimal implementation to get rcutils building
    # Full EmPy template expansion will be added later

    content = """// Generated by generate_logging_macros.py
// Based on ROS2 rcutils upstream template
// Reference: https://github.com/ros2/rcutils/blob/humble/resource/logging_macros.h.em

#ifndef RCUTILS__LOGGING_MACROS_H_
#define RCUTILS__LOGGING_MACROS_H_

#include "rcutils/logging.h"

#ifdef __cplusplus
extern "C"
{
#endif

// ============================================================================
// Severity levels (from rcutils/logging.h)
// ============================================================================
#define RCUTILS_LOG_SEVERITY_DEBUG    10
#define RCUTILS_LOG_SEVERITY_INFO     20
#define RCUTILS_LOG_SEVERITY_WARN     30
#define RCUTILS_LOG_SEVERITY_ERROR    40
#define RCUTILS_LOG_SEVERITY_FATAL    50

// ============================================================================
// Core conditional logging macro (used by all other macros)
// ============================================================================
#define RCUTILS_LOG_COND_NAMED(severity, condition_before, condition_after, name, ...) \\
  do { \\
    RCUTILS_LOGGING_AUTOINIT; \\
    static rcutils_log_location_t __rcutils_logging_location = {__func__, __FILE__, __LINE__}; \\
    if (rcutils_logging_logger_is_enabled_for(name, severity)) { \\
      condition_before \\
      rcutils_log(&__rcutils_logging_location, severity, name, __VA_ARGS__); \\
      condition_after \\
    } \\
  } while (0)

// ============================================================================
// Condition macros
// ============================================================================
#define RCUTILS_LOG_CONDITION_EMPTY

#define RCUTILS_LOG_CONDITION_ONCE_BEFORE \\
  { \\
    static bool __rcutils_logging_once = false; \\
    if (RCUTILS_UNLIKELY(!__rcutils_logging_once)) { \\
      __rcutils_logging_once = true;

#define RCUTILS_LOG_CONDITION_ONCE_AFTER \\
    } \\
  }

#define RCUTILS_LOG_CONDITION_EXPRESSION_BEFORE(expression) \\
  if (expression) {

#define RCUTILS_LOG_CONDITION_EXPRESSION_AFTER }

#define RCUTILS_LOG_CONDITION_SKIPFIRST_BEFORE \\
  { \\
    static bool __rcutils_logging_first = true; \\
    if (RCUTILS_UNLIKELY(true == __rcutils_logging_first)) { \\
      __rcutils_logging_first = false; \\
    } else {

#define RCUTILS_LOG_CONDITION_SKIPFIRST_AFTER \\
    } \\
  }

// ============================================================================
// Basic logging macros (no name)
// ============================================================================
#define RCUTILS_LOG_DEBUG(...) \\
  RCUTILS_LOG_DEBUG_NAMED("", __VA_ARGS__)

#define RCUTILS_LOG_INFO(...) \\
  RCUTILS_LOG_INFO_NAMED("", __VA_ARGS__)

#define RCUTILS_LOG_WARN(...) \\
  RCUTILS_LOG_WARN_NAMED("", __VA_ARGS__)

#define RCUTILS_LOG_ERROR(...) \\
  RCUTILS_LOG_ERROR_NAMED("", __VA_ARGS__)

#define RCUTILS_LOG_FATAL(...) \\
  RCUTILS_LOG_FATAL_NAMED("", __VA_ARGS__)

// ============================================================================
// Named logging macros
// ============================================================================
#define RCUTILS_LOG_DEBUG_NAMED(name, ...) \\
  RCUTILS_LOG_COND_NAMED(RCUTILS_LOG_SEVERITY_DEBUG, RCUTILS_LOG_CONDITION_EMPTY, RCUTILS_LOG_CONDITION_EMPTY, name, __VA_ARGS__)

#define RCUTILS_LOG_INFO_NAMED(name, ...) \\
  RCUTILS_LOG_COND_NAMED(RCUTILS_LOG_SEVERITY_INFO, RCUTILS_LOG_CONDITION_EMPTY, RCUTILS_LOG_CONDITION_EMPTY, name, __VA_ARGS__)

#define RCUTILS_LOG_WARN_NAMED(name, ...) \\
  RCUTILS_LOG_COND_NAMED(RCUTILS_LOG_SEVERITY_WARN, RCUTILS_LOG_CONDITION_EMPTY, RCUTILS_LOG_CONDITION_EMPTY, name, __VA_ARGS__)

#define RCUTILS_LOG_ERROR_NAMED(name, ...) \\
  RCUTILS_LOG_COND_NAMED(RCUTILS_LOG_SEVERITY_ERROR, RCUTILS_LOG_CONDITION_EMPTY, RCUTILS_LOG_CONDITION_EMPTY, name, __VA_ARGS__)

#define RCUTILS_LOG_FATAL_NAMED(name, ...) \\
  RCUTILS_LOG_COND_NAMED(RCUTILS_LOG_SEVERITY_FATAL, RCUTILS_LOG_CONDITION_EMPTY, RCUTILS_LOG_CONDITION_EMPTY, name, __VA_ARGS__)

// ============================================================================
// Expression-conditional logging macros
// ============================================================================
#define RCUTILS_LOG_DEBUG_EXPRESSION(expression, ...) \\
  RCUTILS_LOG_DEBUG_EXPRESSION_NAMED(expression, "", __VA_ARGS__)

#define RCUTILS_LOG_INFO_EXPRESSION(expression, ...) \\
  RCUTILS_LOG_INFO_EXPRESSION_NAMED(expression, "", __VA_ARGS__)

#define RCUTILS_LOG_WARN_EXPRESSION(expression, ...) \\
  RCUTILS_LOG_WARN_EXPRESSION_NAMED(expression, "", __VA_ARGS__)

#define RCUTILS_LOG_ERROR_EXPRESSION(expression, ...) \\
  RCUTILS_LOG_ERROR_EXPRESSION_NAMED(expression, "", __VA_ARGS__)

#define RCUTILS_LOG_FATAL_EXPRESSION(expression, ...) \\
  RCUTILS_LOG_FATAL_EXPRESSION_NAMED(expression, "", __VA_ARGS__)

#define RCUTILS_LOG_DEBUG_EXPRESSION_NAMED(expression, name, ...) \\
  RCUTILS_LOG_COND_NAMED(RCUTILS_LOG_SEVERITY_DEBUG, RCUTILS_LOG_CONDITION_EXPRESSION_BEFORE(expression), RCUTILS_LOG_CONDITION_EXPRESSION_AFTER, name, __VA_ARGS__)

#define RCUTILS_LOG_INFO_EXPRESSION_NAMED(expression, name, ...) \\
  RCUTILS_LOG_COND_NAMED(RCUTILS_LOG_SEVERITY_INFO, RCUTILS_LOG_CONDITION_EXPRESSION_BEFORE(expression), RCUTILS_LOG_CONDITION_EXPRESSION_AFTER, name, __VA_ARGS__)

#define RCUTILS_LOG_WARN_EXPRESSION_NAMED(expression, name, ...) \\
  RCUTILS_LOG_COND_NAMED(RCUTILS_LOG_SEVERITY_WARN, RCUTILS_LOG_CONDITION_EXPRESSION_BEFORE(expression), RCUTILS_LOG_CONDITION_EXPRESSION_AFTER, name, __VA_ARGS__)

#define RCUTILS_LOG_ERROR_EXPRESSION_NAMED(expression, name, ...) \\
  RCUTILS_LOG_COND_NAMED(RCUTILS_LOG_SEVERITY_ERROR, RCUTILS_LOG_CONDITION_EXPRESSION_BEFORE(expression), RCUTILS_LOG_CONDITION_EXPRESSION_AFTER, name, __VA_ARGS__)

#define RCUTILS_LOG_FATAL_EXPRESSION_NAMED(expression, name, ...) \\
  RCUTILS_LOG_COND_NAMED(RCUTILS_LOG_SEVERITY_FATAL, RCUTILS_LOG_CONDITION_EXPRESSION_BEFORE(expression), RCUTILS_LOG_CONDITION_EXPRESSION_AFTER, name, __VA_ARGS__)

// ============================================================================
// ONCE variants (log only on first invocation)
// ============================================================================
#define RCUTILS_LOG_DEBUG_ONCE(msg, ...) \\
  RCUTILS_LOG_DEBUG_ONCE_NAMED("", msg, ##__VA_ARGS__)

#define RCUTILS_LOG_INFO_ONCE(msg, ...) \\
  RCUTILS_LOG_INFO_ONCE_NAMED("", msg, ##__VA_ARGS__)

#define RCUTILS_LOG_WARN_ONCE(msg, ...) \\
  RCUTILS_LOG_WARN_ONCE_NAMED("", msg, ##__VA_ARGS__)

#define RCUTILS_LOG_ERROR_ONCE(msg, ...) \\
  RCUTILS_LOG_ERROR_ONCE_NAMED("", msg, ##__VA_ARGS__)

#define RCUTILS_LOG_FATAL_ONCE(msg, ...) \\
  RCUTILS_LOG_FATAL_ONCE_NAMED("", msg, ##__VA_ARGS__)

#define RCUTILS_LOG_DEBUG_ONCE_NAMED(name, msg, ...) \\
  do { \\
    static bool __rcutils_log_once = false; \\
    if (!__rcutils_log_once) { \\
      __rcutils_log_once = true; \\
      RCUTILS_LOG_DEBUG_NAMED(name, msg, ##__VA_ARGS__); \\
    } \\
  } while (0)

#define RCUTILS_LOG_INFO_ONCE_NAMED(name, msg, ...) \\
  do { \\
    static bool __rcutils_log_once = false; \\
    if (!__rcutils_log_once) { \\
      __rcutils_log_once = true; \\
      RCUTILS_LOG_INFO_NAMED(name, msg, ##__VA_ARGS__); \\
    } \\
  } while (0)

#define RCUTILS_LOG_WARN_ONCE_NAMED(name, msg, ...) \\
  do { \\
    static bool __rcutils_log_once = false; \\
    if (!__rcutils_log_once) { \\
      __rcutils_log_once = true; \\
      RCUTILS_LOG_WARN_NAMED(name, msg, ##__VA_ARGS__); \\
    } \\
  } while (0)

#define RCUTILS_LOG_ERROR_ONCE_NAMED(name, msg, ...) \\
  do { \\
    static bool __rcutils_log_once = false; \\
    if (!__rcutils_log_once) { \\
      __rcutils_log_once = true; \\
      RCUTILS_LOG_ERROR_NAMED(name, msg, ##__VA_ARGS__); \\
    } \\
  } while (0)

#define RCUTILS_LOG_FATAL_ONCE_NAMED(name, msg, ...) \\
  do { \\
    static bool __rcutils_log_once = false; \\
    if (!__rcutils_log_once) { \\
      __rcutils_log_once = true; \\
      RCUTILS_LOG_FATAL_NAMED(name, msg, ##__VA_ARGS__); \\
    } \\
  } while (0)

// ============================================================================
// SKIPFIRST variants (skip first invocation, log subsequent ones)
// ============================================================================
#define RCUTILS_LOG_DEBUG_SKIPFIRST(msg, ...) \\
  RCUTILS_LOG_DEBUG_SKIPFIRST_NAMED("", msg, ##__VA_ARGS__)

#define RCUTILS_LOG_INFO_SKIPFIRST(msg, ...) \\
  RCUTILS_LOG_INFO_SKIPFIRST_NAMED("", msg, ##__VA_ARGS__)

#define RCUTILS_LOG_WARN_SKIPFIRST(msg, ...) \\
  RCUTILS_LOG_WARN_SKIPFIRST_NAMED("", msg, ##__VA_ARGS__)

#define RCUTILS_LOG_ERROR_SKIPFIRST(msg, ...) \\
  RCUTILS_LOG_ERROR_SKIPFIRST_NAMED("", msg, ##__VA_ARGS__)

#define RCUTILS_LOG_FATAL_SKIPFIRST(msg, ...) \\
  RCUTILS_LOG_FATAL_SKIPFIRST_NAMED("", msg, ##__VA_ARGS__)

#define RCUTILS_LOG_DEBUG_SKIPFIRST_NAMED(name, msg, ...) \\
  do { \\
    static bool __rcutils_log_skip = false; \\
    if (__rcutils_log_skip) { \\
      RCUTILS_LOG_DEBUG_NAMED(name, msg, ##__VA_ARGS__); \\
    } else { \\
      __rcutils_log_skip = true; \\
    } \\
  } while (0)

#define RCUTILS_LOG_INFO_SKIPFIRST_NAMED(name, msg, ...) \\
  do { \\
    static bool __rcutils_log_skip = false; \\
    if (__rcutils_log_skip) { \\
      RCUTILS_LOG_INFO_NAMED(name, msg, ##__VA_ARGS__); \\
    } else { \\
      __rcutils_log_skip = true; \\
    } \\
  } while (0)

#define RCUTILS_LOG_WARN_SKIPFIRST_NAMED(name, msg, ...) \\
  do { \\
    static bool __rcutils_log_skip = false; \\
    if (__rcutils_log_skip) { \\
      RCUTILS_LOG_WARN_NAMED(name, msg, ##__VA_ARGS__); \\
    } else { \\
      __rcutils_log_skip = true; \\
    } \\
  } while (0)

#define RCUTILS_LOG_ERROR_SKIPFIRST_NAMED(name, msg, ...) \\
  do { \\
    static bool __rcutils_log_skip = false; \\
    if (__rcutils_log_skip) { \\
      RCUTILS_LOG_ERROR_NAMED(name, msg, ##__VA_ARGS__); \\
    } else { \\
      __rcutils_log_skip = true; \\
    } \\
  } while (0)

#define RCUTILS_LOG_FATAL_SKIPFIRST_NAMED(name, msg, ...) \\
  do { \\
    static bool __rcutils_log_skip = false; \\
    if (__rcutils_log_skip) { \\
      RCUTILS_LOG_FATAL_NAMED(name, msg, ##__VA_ARGS__); \\
    } else { \\
      __rcutils_log_skip = true; \\
    } \\
  } while (0)

#ifdef __cplusplus
}
#endif

#endif  // RCUTILS__LOGGING_MACROS_H_
"""

    # Write output
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w') as f:
        f.write(content)

    print(f"Generated: {output_path}")
    return 0


def main():
    parser = argparse.ArgumentParser(
        description='Generate logging_macros.h from template')
    parser.add_argument('--template', required=True,
                        help='Path to logging_macros.h.em template')
    parser.add_argument('--output', required=True,
                        help='Output path for logging_macros.h')

    args = parser.parse_args()

    return generate_logging_macros(args.template, args.output)


if __name__ == '__main__':
    sys.exit(main())
