#!/usr/bin/env python3
# Copyright (c) 2024 ROS2 OpenHarmony Port Project
# Interface code generator script
#
# This script generates C/C++ code from ROS2 .msg/.srv/.action files
# Run this on the host machine before cross-compiling for OpenHarmony

import argparse
import os
import subprocess
import sys
from pathlib import Path

# Interface packages to generate
INTERFACE_PACKAGES = [
    {
        "name": "builtin_interfaces",
        "path": "ros2/src/ros2/rcl_interfaces/builtin_interfaces",
        "msgs": ["Duration", "Time"],
        "srvs": [],
        "dependencies": [],
    },
    {
        "name": "std_msgs",
        "path": "ros2/src/ros2/common_interfaces/std_msgs",
        "msgs": [
            "Bool", "Byte", "Char", "ColorRGBA", "Empty", "Float32", "Float64",
            "Header", "Int8", "Int16", "Int32", "Int64",
            "MultiArrayDimension", "MultiArrayLayout",
            "String", "UInt8", "UInt16", "UInt32", "UInt64",
            "ByteMultiArray", "Float32MultiArray", "Float64MultiArray",
            "Int8MultiArray", "Int16MultiArray", "Int32MultiArray", "Int64MultiArray",
            "UInt8MultiArray", "UInt16MultiArray", "UInt32MultiArray", "UInt64MultiArray",
        ],
        "srvs": [],
        "dependencies": ["builtin_interfaces"],
    },
    {
        "name": "rcl_interfaces",
        "path": "ros2/src/ros2/rcl_interfaces/rcl_interfaces",
        "msgs": [
            "FloatingPointRange", "IntegerRange", "ListParametersResult",
            "Log", "Parameter", "ParameterDescriptor", "ParameterEvent",
            "ParameterEventDescriptors", "ParameterType", "ParameterValue",
            "SetParametersResult",
        ],
        "srvs": [
            "DescribeParameters", "GetParameters", "GetParameterTypes",
            "ListParameters", "SetParameters", "SetParametersAtomically",
        ],
        "dependencies": ["builtin_interfaces"],
    },
    {
        "name": "rosgraph_msgs",
        "path": "ros2/src/ros2/rcl_interfaces/rosgraph_msgs",
        "msgs": ["Clock"],
        "srvs": [],
        "dependencies": ["builtin_interfaces"],
    },
]


def generate_c_header(package_name, msg_name, output_dir):
    """Generate C header for a message type."""
    header_content = f'''// Auto-generated by generate_interfaces.py
// DO NOT EDIT

#ifndef {package_name.upper()}__{msg_name.upper()}_H_
#define {package_name.upper()}__{msg_name.upper()}_H_

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_runtime_c/string.h"
#include "rosidl_runtime_c/primitives_sequence.h"

#ifdef __cplusplus
extern "C" {{
#endif

// Forward declarations
struct {package_name}__msg__{msg_name};

// Type definition
typedef struct {package_name}__msg__{msg_name} {package_name}__msg__{msg_name};

// Functions
ROSIDL_GENERATOR_C_PUBLIC_{package_name}
bool {package_name}__msg__{msg_name}__init({package_name}__msg__{msg_name} * msg);

ROSIDL_GENERATOR_C_PUBLIC_{package_name}
void {package_name}__msg__{msg_name}__fini({package_name}__msg__{msg_name} * msg);

ROSIDL_GENERATOR_C_PUBLIC_{package_name}
{package_name}__msg__{msg_name} * {package_name}__msg__{msg_name}__create(void);

ROSIDL_GENERATOR_C_PUBLIC_{package_name}
void {package_name}__msg__{msg_name}__destroy({package_name}__msg__{msg_name} * msg);

// Type support
ROSIDL_GENERATOR_C_PUBLIC_{package_name}
const rosidl_message_type_support_t *
ROSIDL_TYPESUPPORT_INTERFACE__MESSAGE_SYMBOL_NAME(
  rosidl_typesupport_c, {package_name}, msg, {msg_name})();

#ifdef __cplusplus
}}
#endif

#endif  // {package_name.upper()}__{msg_name.upper()}_H_
'''

    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, f"{msg_name.lower()}.h")
    with open(output_file, 'w') as f:
        f.write(header_content)
    return output_file


def main():
    parser = argparse.ArgumentParser(description='Generate ROS2 interface code')
    parser.add_argument('--ros2-root', default='.',
                        help='ROS2 source root directory')
    parser.add_argument('--output-dir', default='ohos_ros2/generated',
                        help='Output directory for generated code')
    parser.add_argument('--packages', nargs='*',
                        help='Specific packages to generate (default: all)')
    parser.add_argument('--use-rosidl', action='store_true',
                        help='Use rosidl generators (requires ROS2 environment)')

    args = parser.parse_args()

    ros2_root = Path(args.ros2_root).resolve()
    output_dir = Path(args.output_dir).resolve()

    print(f"ROS2 root: {ros2_root}")
    print(f"Output directory: {output_dir}")

    packages_to_generate = args.packages or [p["name"] for p in INTERFACE_PACKAGES]

    for pkg_info in INTERFACE_PACKAGES:
        pkg_name = pkg_info["name"]
        if pkg_name not in packages_to_generate:
            continue

        print(f"\nGenerating {pkg_name}...")
        pkg_output = output_dir / pkg_name

        if args.use_rosidl:
            # Use rosidl generators (requires ROS2 environment)
            pkg_path = ros2_root / pkg_info["path"]
            cmd = [
                "ros2", "run", "rosidl_generator_c", "rosidl_generator_c",
                "--package-name", pkg_name,
                "--output-dir", str(pkg_output),
            ]
            for msg in pkg_info["msgs"]:
                cmd.extend(["--interface-files", f"{pkg_path}/msg/{msg}.msg"])

            try:
                subprocess.run(cmd, check=True)
            except subprocess.CalledProcessError as e:
                print(f"Error generating {pkg_name}: {e}")
                continue
        else:
            # Generate stub headers (for initial build testing)
            msg_output = pkg_output / "msg"
            for msg in pkg_info["msgs"]:
                output_file = generate_c_header(pkg_name, msg, msg_output)
                print(f"  Generated: {output_file}")

    print("\nGeneration complete!")
    print(f"\nNote: For full functionality, run with --use-rosidl in a ROS2 environment")
    print("or use the pre-built interface packages from a ROS2 installation.")

    return 0


if __name__ == '__main__':
    sys.exit(main())
