/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Copyright 2026 The rmw_dsoftbus Authors
// Licensed under the Apache License, Version 2.0

#ifndef RMW_DSOFTBUS__SERVICE_TYPESUPPORT_SERIALIZER_H_
#define RMW_DSOFTBUS__SERVICE_TYPESUPPORT_SERIALIZER_H_

#include "rmw/types.h"
#include "rosidl_runtime_c/service_type_support_struct.h"

#include <cstdint>
#include <cstddef>

#ifdef __cplusplus
extern "C" {
#endif

/// Serialize a service request with ServiceEnvelope
///
/// Wire format: [ServiceEnvelope: 16 bytes][CDR payload: N bytes]
///
/// @param ros_request The ROS request message (raw C/C++ struct)
/// @param type_support Service type support (must be introspection variant)
/// @param request_id Request ID for correlation (generated by client)
/// @param buffer_out Output buffer (caller must free)
/// @param size_out Output size
/// @return RMW_RET_OK on success, RMW_RET_UNSUPPORTED if typesupport not introspection,
///         RMW_RET_ERROR on serialization failure
rmw_ret_t rmw_dsoftbus_serialize_request(
    const void* ros_request,
    const rosidl_service_type_support_t* type_support,
    uint64_t request_id,
    uint8_t** buffer_out,
    size_t* size_out);

/// Serialize a service response with ServiceEnvelope
///
/// Wire format: [ServiceEnvelope: 16 bytes][CDR payload: N bytes]
///
/// @param ros_response The ROS response message (raw C/C++ struct)
/// @param type_support Service type support (must be introspection variant)
/// @param request_id Request ID from the original request (echoed back)
/// @param buffer_out Output buffer (caller must free)
/// @param size_out Output size
/// @return RMW_RET_OK on success, RMW_RET_UNSUPPORTED if typesupport not introspection,
///         RMW_RET_ERROR on serialization failure
rmw_ret_t rmw_dsoftbus_serialize_response(
    const void* ros_response,
    const rosidl_service_type_support_t* type_support,
    uint64_t request_id,
    uint8_t** buffer_out,
    size_t* size_out);

/// Deserialize a service request from wire format
///
/// @param buffer Input buffer (ServiceEnvelope + CDR payload)
/// @param size Input size
/// @param type_support Service type support (must be introspection variant)
/// @param request_id_out Output request ID from envelope
/// @param ros_request_out Output ROS request message (must be pre-allocated)
/// @return RMW_RET_OK on success, RMW_RET_UNSUPPORTED if typesupport not introspection,
///         RMW_RET_ERROR on deserialization failure
rmw_ret_t rmw_dsoftbus_deserialize_request(
    const uint8_t* buffer,
    size_t size,
    const rosidl_service_type_support_t* type_support,
    uint64_t* request_id_out,
    void* ros_request_out);

/// Deserialize a service response from wire format
///
/// @param buffer Input buffer (ServiceEnvelope + CDR payload)
/// @param size Input size
/// @param type_support Service type support (must be introspection variant)
/// @param request_id_out Output request ID from envelope (for correlation verification)
/// @param ros_response_out Output ROS response message (must be pre-allocated)
/// @return RMW_RET_OK on success, RMW_RET_UNSUPPORTED if typesupport not introspection,
///         RMW_RET_ERROR on deserialization failure
rmw_ret_t rmw_dsoftbus_deserialize_response(
    const uint8_t* buffer,
    size_t size,
    const rosidl_service_type_support_t* type_support,
    uint64_t* request_id_out,
    void* ros_response_out);

/// Get the request message type support from a service type support
///
/// @param service_type_support Service type support
/// @return Message type support for request, or NULL if not available/unsupported
const rosidl_message_type_support_t* rmw_dsoftbus_get_request_typesupport(
    const rosidl_service_type_support_t* service_type_support);

/// Get the response message type support from a service type support
///
/// @param service_type_support Service type support
/// @return Message type support for response, or NULL if not available/unsupported
const rosidl_message_type_support_t* rmw_dsoftbus_get_response_typesupport(
    const rosidl_service_type_support_t* service_type_support);

#ifdef __cplusplus
}
#endif

#endif  // RMW_DSOFTBUS__SERVICE_TYPESUPPORT_SERIALIZER_H_
